Add missing libtcl8.6 `stage-packages`
```
application-specific initialization failed: Can't find a usable init.tcl in the following directories:
    /usr/share/tcltk/tcl8.6 /snap/git-cola-brlin/x19/usr/lib/tcl8.6 /snap/git-cola-brlin/x19/lib/tcl8.6 /snap/git-cola-brlin/x19/usr/library /snap/git-cola-brlin/x19/library /snap/git-cola-brlin/x19/tcl8.6.5/library /snap/git-cola-brlin/tcl8.6.5/library

This probably means that Tcl wasn't installed properly.

Error in startup script: can't find package Tk
    while executing
"package require Tk"
    (file "/snap/git-cola-brlin/x19/share/git-cola/bin/ssh-askpass" line 8)
error: unable to read askpass response from '/snap/git-cola-brlin/x19/share/git-cola/bin/ssh-askpass'
fatal: could not read Username for 'https://github.com': No such device or address
```

Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>